views/traveler.py
from flask import request, session, g, redirect, url_for, \
     render_template, flash, Blueprint
from bikeandwalk import db, app
from views.utils import nowString
from models import Traveler, EventTraveler, TravelerFeature, Feature, Trip
from views.utils import printException, cleanRecordID
from views.trip import getEventTravelerTripTotal
from forms import EventTravelerForm

mod = Blueprint('traveler',__name__)


def setExits():
    g.listURL = url_for('.display')
    g.editURL = url_for('.edit')
    g.deleteURL = url_for('.delete')
    g.title = 'Traveler'

@mod.route('/traveler/')
def display():
    if db :
        rec = Traveler.query.all()
        setExits()
        return render_template('traveler/traveler_list.html', recs=rec)

    flash('Could not open Database')
    return redirect(url_for('home'))
    

@mod.route('/traveler/edit', methods=['POST', 'GET'])
@mod.route('/traveler/edit/', methods=['POST', 'GET'])
@mod.route('/traveler/edit/<id>/', methods=['POST', 'GET'])
def edit(id=0):
    setExits()
    id = cleanRecordID(id)
    if id < 0:
        flash("That is not a valid ID")
        return redirect(g.listURL)
    
    if not request.form:
        """ if no form object, send the form page """
        # get the Org record if you can
        rec = None
        if id > 0:
            rec = Traveler.query.get(id)
        #get a cursor of all features
        features = getFeatureSet(id)

        return render_template('traveler/traveler_edit.html', rec=rec, features=features, lastFeature=len(features))

    #have the request form
    if validForm():
        if id > 0:
            rec = Traveler.query.get(id)
        else:
            ## create a new record stub
            rec = Traveler(request.form['name'],request.form['travelerCode'])
            db.session.add(rec)
        try:
            db.session.commit() ## ID now has a value
        except Exception as e:
            db.session.rollback()
            flash(printException('Could not '+g.title+' record.',"error",e))
            return redirect(g.listURL)
            
        #update the record
        rec.name = request.form['name']
        rec.travelerCode = request.form['travelerCode']
        rec.description = request.form['description']
        rec.iconURL = request.form['iconURL']
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash(printException('Could not Update '+g.title+' record (ID ='+str(id)+').',"error",e))
            return redirect(g.listURL)
            
        id = rec.ID
        
        # now update the features
        #delete the old ones first
        tf = TravelerFeature.query.filter_by(traveler_ID = str(id)).delete(synchronize_session='fetch')
        try:
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash(printException('Could not Delete Feature records for '+g.title+' record (ID ='+str(id)+').',"error",e))
            return redirect(g.listURL)
           
        #create new ones
        featureSet = request.form.getlist('featureSet')
        for feat in featureSet:
            tf = TravelerFeature(id,int(feat))
            db.session.add(tf)
            
        try:
            db.session.commit()    
        except Exception as e:
            db.session.rollback()
            flash(printException('Could not Create Feature records for '+g.title+' record (ID ='+str(id)+').',"error",e))
            return redirect(g.listURL)
                 
        return redirect(g.listURL)

    # form not valid - redisplay
    features = getFeatureSet(id)
    app.logger.info("Feature set len = " +str(features))
    return render_template('traveler/traveler_edit.html', rec=request.form, features=features, lastFeature=len(features))


@mod.route('/traveler/delete/', methods=['GET'])
@mod.route('/traveler/delete/<id>/', methods=['GET'])
def delete(id=0):
    setExits()
    id = cleanRecordID(id)
    if id < 0:
        flash("That is not a valid ID")
        return redirect(g.listURL)
 
    rec = Traveler.query.get(id)
    if rec:
        ## Can't delete Traveler that has been used in a trip
        trip = Trip.query.filter_by(traveler_ID = str(id)).all()
        if trip:
            #can't delete
            flash("You can't delete this Traveler because there are Trip records that use it")
            return redirect(g.listURL)
        
        # Delete the related records
        et = EventTraveler.query.filter_by(traveler_ID = str(id)).delete(synchronize_session='fetch')
        tf = TravelerFeature.query.filter_by(traveler_ID = str(id)).delete(synchronize_session='fetch')
        ## delete the traveler
    try:
        db.session.delete(rec)
        db.session.commit()
    except Exception as e:
        flash(printException('Error attempting to delete '+g.title+' record.',"error",e))
        db.session.rollback()

    return redirect(g.listURL)

    
def validForm():
    # Validate the form
    goodForm = True

    if request.form['travelerCode'] == '':
        goodForm = False
        flash('Traveler Code may not be blank')
        
    if request.form['travelerCode'] != '':
        val = Traveler.query.filter(Traveler.travelerCode == request.form['travelerCode'], Traveler.ID != request.form['ID']).count()
        if val > 0:
            goodForm = False
            flash('That Traveler Code is in use already')
            
    if len(request.form.getlist('featureSet')) == 0:
            goodForm = False
            flash('You must select at least one Feature')
        
    return goodForm
    
def getFeatureSet(id=0):
    f = Feature.query.all()
    rows = Feature.query.count()
    #app.logger.info("Row Count = " + str(rows))
    records = dict()
    for elem in range(rows):
        feature = dict()
        feature['ID'] = f[elem].ID
        feature['featureClass'] = f[elem].featureClass
        feature['featureValue'] = f[elem].featureValue
        feature['featureSelected'] = False
        if id > 0:
            tf = TravelerFeature.query.filter_by(traveler_ID = id, feature_ID = f[elem].ID).all()
            if tf:
                feature['featureSelected'] = True
        records[elem] = feature
    return records

## return an HTML code segment to include in the count_event edit form
@mod.route("/eventtraveler/getTravelerList", methods=['GET'])
@mod.route("/eventtraveler/getTravelerList/<countEventID>/", methods=['GET','POST'])
def getTravelerList(countEventID = 0):
    countEventID = cleanRecordID(countEventID)
    out = ""

    if countEventID > 0:
        recs = getEventTravelers(countEventID)
        if recs:
            for eventTraveler in recs:
                traveler = Traveler.query.get(eventTraveler.traveler_ID)
                if traveler:
                    totalTrips = getEventTravelerTripTotal(countEventID, traveler.ID)
                    out += render_template('traveler/travelerListElement.html', eventTraveler=eventTraveler, traveler=traveler, totalTrips=totalTrips)

    return out

@mod.route('/eventtraveler/removeFromList', methods=["GET","POST"])
@mod.route('/eventtraveler/removeFromList/<eventTravelerID>/', methods=["GET","POST"])
def removeFromList(eventTravelerID):
    eventTravelerID=cleanRecordID(eventTravelerID)
    if eventTravelerID > 0:
        # remove the event_traveler record only if there are no trips for this traveler / event
        rec = EventTraveler.query.get(eventTravelerID)
        if rec:
            tripCnt = getEventTravelerTripTotal(eventTravelerID, rec.traveler_ID)
            if tripCnt == 0:
                db.session.delete(rec)
                db.session.commit()
                return "success"

    return "failure: Unable to Remove that record."
    
    
@mod.route("/eventTraveler/selectNew/", methods=['GET'])
@mod.route("/eventTraveler/selectNew/<countEventID>/", methods=['GET'])
def newEventTraveler(countEventID=0):
    g.countEventID =cleanRecordID(countEventID)
    return editEventTraveler(0)
    
## editing list called from within countEvent form
@mod.route("/eventTraveler/editFromList", methods=['GET',"POST"])
@mod.route("/eventTraveler/editFromList/<eventTravelerID>/", methods=['GET',"POST"])
def editEventTraveler(eventTravelerID=0):
    setExits()
    data = None
    rec = None
    traveler = None

    if request.form:
        eventTravelerID = cleanRecordID(request.form["ID"])
        g.countEventID = cleanRecordID(request.form["countEvent_ID"])
    else:
        eventTravelerID = cleanRecordID(eventTravelerID)
        
    travelerName = ""
    if eventTravelerID > 0:
        rec = EventTraveler.query.get(eventTravelerID)
        if rec:
            g.countEventID = rec.countEvent_ID
            traveler = Traveler.query.get(rec.traveler_ID)
            travelerName = traveler.name
            
#    print eventTravelerID
#    print g.countEventID
        
    if g.countEventID <= 0:
        return "failure: No Count Event ID was found."

    availableTravelers = None 
    if eventTravelerID == 0:
        #If creating a new record, get a list of unused travelers

        sql = 'select ID,name from traveler \
            where  \
            ID not in \
               (select traveler_ID from event_traveler where countEvent_ID  = %d);' \
            % (g.countEventID)

        ## It's important to call fetchcll() or fetchone() after executing sql this way or the
        ##  database will be left in a locked state.
        availableTravelers = db.engine.execute(sql).fetchall()
        if len(availableTravelers) == 0:
            return "failure: There are no more Travelers to use."
    
    travelerOrder = None
    #get a list of all the sort orders for the current set of travelers for this event
    et = getEventTravelers(g.countEventID)
    travelerOrder = []
    elem = {"travelerName" : "1st in list", "sortOrder": 0}
    lastSortOrder = 0
    travelerOrder.append(elem)
    for t in et:

templates/count_event/count_event_edit.html
{% extends "layout.html" %}
{% block title %}Edit {{ g.title }}{% endblock %}
{% block head %}
<script src="{{ url_for('static', filename='jquery-ui-1.11.4.custom/jquery-ui.min.js') }}"></script>
<link rel=stylesheet type=text/css href="{{ url_for('static', filename='jquery-ui-1.11.4.custom/jquery-ui.css') }}">
<script type="text/javascript">
	$(document).ready(function(){
		$('#datepicker').datepicker({inline:true,
			dateFormat: "yy-mm-dd",
			onSelect: function(dateText) {
				$("#eventDate").val(dateText);
			  },
		});
		$( "#datepicker" ).datepicker( "setDate", "{{ theTime["eventDate"]}}" );
	});
</script>
{% endblock head %}
{% block body %}
<h2>
	Edit {{ g.title }}
	{% if g.tripTotalCount and g.tripTotalCount > 0 %}
		<span id="tripTotalCount">(Total Count: {{ g.tripTotalCount}})</span>
	{% endif %}
</h2>	
<div id="eventRecordForm">
	    <form action="{{ g.editURL }}{{rec.ID|default("0",true)}}/" method=post class="entry">
		<input type=hidden name="ID" value="{{rec.ID|default("0",true)}}">
		<input type=hidden name="organization_ID" value="{{rec.organization_ID|default(g.orgID,true)}}">
		{% include "editFormButtons.html" %}
        <p>Title: </p>
		<p><input type=text size=30  name="title" value="{{rec.title}}" /></p>
		<div id="datepicker" ></div>
		<p><input type="hidden" value="{{theTime.eventDate }}" id="eventDate" name="eventDate" /></p>
        <p><strong>Starting Time:</strong></p>
		<p>
			<select name="hour">
				{% for i in range(1,13) %}
				<option value="0{{i}}" {% if theTime.hour == i %}selected="selected" {% endif %}>{{i}}</option>
				{% endfor %}
			</select>
			<select name="minute">
				<option value="00" {% if theTime.minute == 0 %}selected="selected" {% endif %}>00</option>
				<option value="15" {% if theTime.minute == 15 %}selected="selected" {% endif %}>15</option>
				<option value="30" {% if theTime.minute == 30 %}selected="selected" {% endif %}>30</option>
				<option value="45" {% if theTime.minute == 45 %}selected="selected" {% endif %}>45</option>
			</select>
			<select name="AMPM">
				<option value="AM" {% if theTime.AMPM == "AM" %}selected="selected" {% endif %}>AM</option>
				<option value="PM" {% if theTime.AMPM == "PM" %}selected="selected" {% endif %}>PM</option>
			</select>
		</p>
		<p><strong>Duration:</strong></p>
		<p>
			<select name="duration" >
				<option value="1" {% if theTime.duration == 1 %}selected="selected" {% endif %}>1 Hour</option>
				{% for i in range(2,9) %}
					<option value="{{i}}" {% if theTime.duration == i %}selected="selected" {% endif %}>{{i}} Hours</option>
				{% endfor %}
			</select>
		</p>
		<p><strong>Time Zone:</strong></p>
		<p>
	        <select name="timeZone">
			{% for zone in timeZones.keys() %}
				<option value="{{zone}}" {%if rec.timeZone == zone or (g.timeZone and g.timeZone == zone )%}selected="selected"{%endif%} >{{timeZones[zone]["longName"]}} ({{zone}})</option>
			{% endfor %}
			</select>
		</p>
		<p>
			<span class="smallprint">Will it be Daylight Savings time? </span><br>
			<input type="radio" name="isDST" value="0" {%if rec.isDST != 1 %}checked="checked"{%endif%} id="DSTno" /> <label class="smallprint" for="DSTno">No</label>
			<input type="radio" name="isDST" value="1" {%if rec.isDST == 1 %}checked="checked"{%endif%} id="DSTyes" /> <label class="smallprint" for="DSTyes">Yes</label>
		</p>
		<p><strong>Weather:</strong> <span class="smallprint">(Set after the count)</span></p>
		<p>
			<select name="weather">
				<option value="" {% if rec.weather == "" %}selected="selected"{% endif %}>Select After the Count</option>
				<option value="Fair" {% if rec.weather == "Fair" %}selected="selected"{% endif %}>Fair</option>
				<option value="Rainy" {% if rec.weather == "Rainy" %}selected="selected"{% endif %}>Rainy</option>
				<option value="Very Cold" {% if rec.weather == "Very Cold" %}selected="selected"{% endif %}>Very Cold</option>
			</select>
		</p>
    </form>
</div> <!--Event record form -->
<div id="travelerListContain">
	<h3>Traveler List</h3>
	<div id="travelerList">
		{{travelerList | safe }}
	</div>
	<p class="script-link" 
		onclick="editFromList('{{url_for("traveler.newEventTraveler")}}{{rec.ID|default("0",true)}}')"
		>Select a new Traveler...
	</p>
</div>

{% if rec.ID > 0 %}
<div id="assignment-contain" class="clearer" >
	<h3>Location List</h3>
	<p>
		<span class="editAssignmentFromList script-link" onclick="editFromList('{{ url_for('assignment.createFromList')}}/{{rec.ID}}/')">Add a Location...</span>
		&nbsp;&nbsp;
	</p>
	
<div id="assignmentList">
		{{ assignmentList | safe }}
</div>
</div>
{% endif %}
{% endblock body %}

templates/count_event/count_event_list.html
{% extends "layout.html" %}
{% block title %}{{ g.title }} List{% endblock %}
{% block body %}
	<h2>{{g.title}} List</h2>
	{%if recs %}
		<table class="datatable">
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Date</th>
			<th>Start Time</th>
			<th>End Time</th>
			<th>Dup.</th>
		</tr>
		{% for rec in recs %}
	    <tr>
			<td><a href="{{ g.editURL }}{{ rec.ID }}/">{{ rec.ID }}</a></td>
			<td><a href="{{ g.editURL }}{{ rec.ID }}/">{{ rec.title | default("Untitled", True) }}</a></td>
			<td>{{ theTime[rec.ID]["longStartDate"]}}</td>
			<td>{{ theTime[rec.ID]["hour"]}}:{{ theTime[rec.ID]["strMinute"]}} {{ theTime[rec.ID]["AMPM"]}}</td>
			<td>{{ theTime[rec.ID]["hourEnd"]}}:{{ theTime[rec.ID]["strMinuteEnd"]}} {{ theTime[rec.ID]["AMPMEnd"]}}</td>
			<td><a href="{{ url_for('.duplicate')}}{{ rec.ID }}">Duplicate this event</a></td>
		</tr>
		{% endfor %}
	  </table>
  	{% else %}
    	<p><em>No {{ g.title }}s here so far</em></p>
	{% endif %}
  	<p id="addRecord"><a href="{{ g.createURL }}">Add a new {{ g.title }}</a></p>
{% endblock body %}