views/assignment.py
from flask import request, session, g, redirect, url_for, \
     render_template, flash, Blueprint, abort
from bikeandwalk import db, app
from models import Assignment, Location, User, CountEvent, Trip, Traveler
from views.utils import printException, getDatetimeFromString, nowString, getUserChoices, getCountEventChoices, \
    getLocationChoices, cleanRecordID
from forms import AssignmentForm, AssignmentEditFromListForm
import hmac
from datetime import datetime
from views.trip import getAssignmentTripTotal
from views.traveler import getTravelersForEvent
from datetime import timedelta

mod = Blueprint('assignment',__name__)

def setExits():
    g.listURL = url_for('.display')
    g.editURL = url_for('.edit')
    g.deleteURL = url_for('.delete')
    g.title = 'Assignment'
    
    
@mod.route("/super/assignment/", methods=['GET'])
@mod.route("/super/assignment", methods=['GET'])
def display():
    setExits()
    if db :
        recs = None
        cl = Assignment.query.filter(Assignment.organization_ID == g.orgID).order_by(Assignment.eventStartDate.desc())
        # collect additional data for each record
        if cl:
            recs = dict()
            for row in cl:
                base = str(row)
                recs[base] = dict()
                recs[base]["ID"] = row.ID
                recs[base]['UID'] = row.assignmentUID
                recs[base]['startDate'] = getDatetimeFromString(row.eventStartDate).strftime('%x @ %I:%M %p')
                recs[base]["location"] = row.locationName
                recs[base]["userName"] = row.userName
                    
        return render_template('assignment/assignment_list.html', recs=recs)
        
    else:
        flash(printException('Could not open Database',"info"))
        return redirect(url_for('home'))
        

@mod.route("/super/assignment/edit/", methods=['GET'])
@mod.route("/super/assignment/edit/<id>", methods=['GET','POST'])
@mod.route("/super/assignment/edit/<id>/", methods=['GET','POST'])
def edit(id="0"):
    setExits()
    id = cleanRecordID(id)
    if id < 0:
        flash("That is not a valid ID")
        return redirect(g.listURL)
        
    rec = None
    if id > 0:
        rec = Assignment.query.get(id)
        if not rec:
            flash(printException("Could not edit that "+g.title + " record. ID="+str(id)+")",'error'))
            return redirect(g.listURL)
    
    form = AssignmentForm(request.form, rec)
        
    ## choices need to be assigned before rendering the form
    # AND before attempting to validate it
    form.user_ID.choices = getUserChoices()
    form.countEvent_ID.choices = getCountEventChoices()
    form.location_ID.choices = getLocationChoices()
    g.AssignedUserIDs = ()
    if rec: 
        g.AssignedUserIDs = getAssignedUsers(int(rec.countEvent_ID))

    if request.method == 'POST' and form.validate():
        if not rec:
            rec = createNewRecord(form.countEvent_ID.data)
            if not rec:
                return redirect(g.listURL)
                    
        form.populate_obj(rec)
        db.session.commit()
        return redirect(g.listURL)
        
    return render_template('genericEditForm.html', rec=rec, form=form)
    
    
@mod.route("/assignment/delete/", methods=['GET'])
@mod.route("/assignment/delete/<id>", methods=['GET','POST'])
@mod.route("/assignment/delete/<id>/", methods=['GET','POST'])
def delete(id="0"):
    setExits()
    id = cleanRecordID(id)
    
    if id < 0:
        flash("That is not a valid ID")
        return redirect(g.listURL)
                        
    if deleteRecordID(id):
        pass
    else:
        flash(printException("Could not delete that "+g.title + " record ID="+str(id)+" could not be found.","error"))
        
    return redirect(g.listURL)
    
def getAssignedUsers(id=0):
    """ A list of the User IDs for those who are already
    assigned to a location for this event
    """
    a = [x.user_ID for x in Assignment.query.filter(Assignment.countEvent_ID == id) ]
    return a

## return an HTML code segment to include in the count_event edit form
@mod.route("/assignment/getAssignmentList", methods=['GET'])
@mod.route("/assignment/getAssignmentList/<countEventID>/", methods=['GET','POST'])
def getAssignmentList(countEventID=0):
    countEventID = cleanRecordID(countEventID)
    out = ""
    
    if countEventID > 0:
        recs = Assignment.query.filter(Assignment.countEvent_ID==countEventID).order_by(Assignment.locationName)
        if recs:
            out = ""
            for rec in recs:
                totalTrips = getAssignmentTripTotal(rec.countEvent_ID, rec.location_ID)
                out += render_template('assignment/listElement.html', rec=rec, totalTrips=totalTrips)
            
    return out
    
@mod.route("/assignment/createFromList", methods=['GET',"POST"])
@mod.route("/assignment/createFromList/<countEventID>/", methods=['GET',"POST"])
def createFromList(countEventID="0"):
    """
    Create a new Assignment record from the CountEvent edit form
    """
    #the template popupEditForm will substitue this for the missing countEvent_ID
    g.countEventID = cleanRecordID(countEventID)
    return editFromList(0)
    
    
## editing list called from within countEvent form
@mod.route("/assignment/editFromList", methods=['GET',"POST"])
@mod.route("/assignment/editFromList/<id>/", methods=['GET',"POST"])
def editFromList(id="0"):
    """
        handle the editing from the count event form.
        Intended for use with AJAX request
        There should always be POST data
    """
    ## when creating a new record, g.countEventID will contain the ID of the countEvent record
    setExits()
    
    data = None
    if not data:
        data = request.form
        
    if "ID" in data:
        id = data["ID"]
    
    id = cleanRecordID(id)
    if id < 0:
        flash("Invalid Record ID")
        return redirect(g.listURL)
        
    locations = None
    if id == 0:
        if "countEvent_ID" in data:
            g.countEventID = data["countEvent_ID"]
            
        ceID = cleanRecordID(g.countEventID)
        g.orgID = cleanRecordID(g.orgID)
        
        ## It's important to call fetchAll() or fetchOne() after executing sql this way or the
        ##  database will be left in a locked state.
        
        sql = 'select ID,locationName from location where organization_ID = %d \
               and ID not in \
               (select location_ID from assignment where countEvent_ID  = %d) \
               order by locationName;' \
            % (g.orgID, ceID)
        
        locations = db.engine.execute(sql).fetchall()
        if len(locations) == 0:
            return "failure: There are no more Locations to use."
        
        
    rec = None
    if id > 0:
        rec = Assignment.query.get(id)
        if not rec:
            flash(printException("Could not edit that "+g.title + " record. (ID="+str(id)+")",'error'))
            return redirect(g.listURL)
    
    form = AssignmentEditFromListForm(data, rec)
        
    ## choices need to be assigned before rendering the form
    # AND before attempting to validate it
    form.user_ID.choices = getUserChoices()        

    if request.method == "POST" and form.validate():
        if not rec:
            rec = createNewRecord(form.countEvent_ID.data)
            if  not rec:
                return "failure: Unable to create a new Assignment record"
                
        rec.location_ID = form.location_ID.data
        rec.countEvent_ID = form.countEvent_ID.data
        rec.user_ID = form.user_ID.data
        try:
            db.session.commit()
        except Exception as e:
            printException("Unable to save Assignment from list", "error", e)
            return "failure: Sorry. Unable to save your changes."
            
        return "success" # the success function looks for this...
        
            
    assignedUserIDs = ()
    if rec: 
        g.countEventID = int(rec.countEvent_ID)
        
    assignedUserIDs = getAssignedUsers(g.countEventID)
    return render_template('assignment/popupEditForm.html', 
        form=form, 
        locations=locations, 
        assigned=assignedUserIDs, 
        )
    
@mod.route('/assignment/editTripsFromList', methods=["GET","POST"])
@mod.route('/assignment/editTripsFromList/<id>/', methods=["GET","POST"])
def editTripsFromList(id):
    setExits()
    tripData = {} #empty dictionary
    id=cleanRecordID(id)
    if id > 0:
        rec = Assignment.query.get(id)
        if not rec:
            return "failure: Assignment record not found"
            
        tripCount = getAssignmentTripTotal(id)
        if tripCount > 0:
            return "failure: There are already trips recorded."
        
        # Get travelers
        travelers = getTravelersForEvent(rec.countEvent_ID)        
        
        #populate tripData with info on manually enterd counts
        tripData = getTurnData(rec)
        countEvent = CountEvent.query.get(rec.countEvent_ID)
        
        timeFrames = getTripTimeFrames(getDatetimeFromString(countEvent.startDate),getDatetimeFromString(countEvent.endDate))
        
        if request.method == "POST":
            # Validate form?
            result = True
            # record trips
            for countInputName in tripData.keys():
                if not request.form[countInputName]:
                    tripCount = 0
                else:
                    tripCount = request.form[countInputName]

                turnLeg = tripData[countInputName][1]
                travelerID = tripData[countInputName][2]
                try:
                    tripCount = int(tripCount) #this may throw a ValueError
                    if tripCount < 0:
                        result = False
                        raise ValueError("Negative values are not allowed.")
                        
                    if tripCount != tripData[countInputName][0]:

templates/assignment/assignment_list.html
{% extends "layout.html" %}
{% block title %}{{ g.title }} List{% endblock %}
{% block body %}
	<h2>{{ g.title }} List</h2>
	{%if recs %}
		<table class="datatable">
		<tr>
			<th>ID</th>
			<th>Start Date</th>
			<th>Location</th>
			<th>UID</th>
			<th>Counter</th>
		</tr>
		{% for rec in recs %}
	    <tr>
			<td><a href="{{ g.editURL }}{{ recs[rec]["ID"] }}/">{{ recs[rec]["ID"] }}</a></td>
			<td><a href="{{ g.editURL }}{{ recs[rec]["ID"] }}/">{{ recs[rec]["startDate"] }}</a></td>
			<td>{{ recs[rec]["location"]}}</td>
			<td>{{ recs[rec]["UID"] }}</td>
			<td>{{ recs[rec]["userName"]|default("Unassigned",true)}}</td>
		</tr>
		{% endfor %}
	  </table>
  	{% else %}
    	<p><em>No {{ g.title }}s here so far</em></p>
	{% endif %}
  	<p id="addRecord"><a href="{{ g.editURL }}0/">Add a new {{ g.title }}</a></p>
{% endblock body %}

templates/assignment/editTrips.html
{# Form to add trips from Assignment List of Event form #}

<h3>Edit Trips for {{rec.locationName}}</h3>
<form id="assignment-edit-trips-form"  action="" method="POST">
{% include "flasher.html" %}
	<input type="hidden" name="ID" value="{{ rec.ID }}">
	<table class="assignment-edit-trips">
	{% for traveler in travelers %}
		<tr>
			<th rowspan="4">
				<p>{{ traveler.name }}</p>
				<p><img class="travelerIcon" src="{{traveler.iconURL|default("//bikeandwalk.org/images/travelers/unknown.png",true)}}" /></p>
			</th>
			<th>Leg A</th>
			<th>Leg B</th>
		</tr>
		<tr>
			{% for d in ("A", "B")%}
			<td>
				{% include 'assignment/editTripsInputInclude.html' %}
			</td>
			{% endfor %}
		</tr>
		<tr>
		<th>Leg C</th>
		<th>Leg D</th>
		</tr>
		<tr>
			{% for d in ("C", "D")%}
			<td>
				{% include 'assignment/editTripsInputInclude.html' %}
			</td>
			{% endfor %}
		</tr>
		<tr style="border:0;" ><td colspan="3" style="border:0;">&nbsp;</td></tr>
	{% endfor %} {# travelers #}
	</table>
	<div class="assignment-buttons data-element">
		<p>
		<span class="cancel-link" onclick="cancelModalForm()">Cancel</span>
		<input class="assignmentSave" type="button" onclick="submitModalForm('assignment-edit-trips-form', '{{ url_for('assignment.editTripsFromList')}}/{{ rec.ID }}/', 'assignmentList', '{{ url_for('assignment.getAssignmentList')}}/{{ rec.countEvent_ID}}/')" name="Save" value="Save" />
		</p>
	</div>
</form>

templates/assignment/editTripsInputInclude.html
{# creates the input form elements used to edit trip data from the assignment form #}
<table class="assignment-edit-trips-data">
	<tr>
		{% if d == "A" or d == "C" %}
		<th class="assignment-edit-trips-timeFrame-cell">Time</th>
		{% endif %}
		{% for c in range(1,4) %}
		{% set turnDir = "%s%d"|format(d,c) %}
		<th>{{turnDir}}</th>
		{% endfor %} {# turn dir header row #}
	</tr>

		{%for timeFrame in timeFrames %}
		<tr>
			{% if d == "A" or d == "C" %}
			<td class="assignment-edit-trips-timeFrame-cell" >{{ timeFrame }}</td>
			{% endif %}
			{% for c in range(1,4) %}
			{% set turnDir = "%s%d"|format(d,c) %}
			{% set inputName = "%d-%s-%s"|format(traveler.ID,turnDir,timeFrame) %}
			<td><input name="{{ inputName }}" type="num" value="{% if tripData[inputName] %}{{ tripData[inputName][0] }}{% else %}-2{% endif %}" /></td>
			{% endfor %}
		</tr>
		
		{% endfor %}

</table>

templates/assignment/listElement.html
{# A single element in the Assignment list used in the count event form #}
{% if rec %}
<div class="assignmentListRow" id="assignmentListItem_{{rec.ID}}" >
	<p><strong>Location:</strong> {{ rec.locationName }}</p>
	<p><strong>Assignment UID:</strong> <code>{{ rec.assignmentUID }}</code></p>
	<p><strong>Assigned To:</strong> 
		<span {% if rec.user_ID == 0 %}class="alert"{% endif %}>{{ rec.userName |default("Unassigned",true)}}</span>
		<span class="assignmentActionSpacer">&nbsp;</span>
		<span class="assignmentActions script-link"
			{% if not rec.userName %}
			onclick="if(confirm('No one assiged. Would you like to do that now?')){
				editFromList('{{ url_for('assignment.editFromList')}}/{{rec.ID}}/');
			}"
			{% else %}
			onclick="if(confirm('Send Invitation Email to {{ rec.userName }}?')){
				sendAssignmentEmail('{{ url_for('count_event.sendAssignmentEmail') }}/{{ rec.ID }}/');
				// refresh the whole assignment list...
				$('#assignmentList').load('{{ url_for('assignment.getAssignmentList') }}/{{ rec.countEvent_ID }}/');
				}"
			{% endif %}
			>Send Invitation 
		</span>{% if rec.invitationSent != "" %}&nbsp;(Sent - {{rec.invitationSent}}){%endif%}
	</p>
	<p class="assignmentActions">
		<span class="assignmentEditTrips script-link" onclick="editFromList('{{ url_for('assignment.editTripsFromList')}}/{{ rec.ID }}/');">Enter Trips</span>
		<span class="assignmentActionSpacer">&nbsp;</span>
	{% if totalTrips == 0 %}
		<span class="assignmentDeleteFromList script-link" 
		onclick="deleteFromList('{{ url_for('assignment.deleteFromList')}}/{{ rec.ID }}/','assignmentListItem_{{rec.ID}}')"
		>Remove Location...
		</span>
		<span class="assignmentActionSpacer">&nbsp;</span>
	{% else %}
		<span class="assignmetnTotalTrips">Trips Recorded: {{totalTrips}}</span>
		<span class="assignmentActionSpacer">&nbsp;</span>
	{% endif %}
	<span class="editAssignmentFromList script-link" 
		onclick="editFromList('{{ url_for('assignment.editFromList')}}/{{rec.ID}}/')"
		>Edit Assignment...
	</span>
	</p>
</div>
{% endif %}

templates/assignment/popupEditForm.html
{# assignment form for response to AJAX request #}
<form id="assignmentFromListForm"  action="" method="POST">
	<input type="hidden" name="ID" value="{{ form.ID.data | default(0,True)}}">
	<input type="hidden" name="countEvent_ID" value="{{ form.countEvent_ID.data | default(g.countEventID,True)}}">
	{% if locations %}
	<p><span class="field-label">{{ form.locationName.label }}: </span></p>
	<select name="location_ID">
		<option value="0">Choose a location</option>
		{% for loc in locations %}
		<option value="{{loc.ID}}" >{{ loc.locationName }}</option>
		{% endfor %}
	</select>
	{% else %}
	{{ form.location_ID }}
	{{ form.locationName }} {# input must be in form as input or name will be blank after validation errors #}
	<div class="data-element">
		<p><span class="field-label">{{ form.locationName.label }}: </span>{{ form.locationName.data }}</p>
	</div>
	{% endif %}
	<div class="data-element">
		{# Disable users in select who are already assigned to this event #}
		<p><span class="field-label">{{ form.user_ID.label }}: </span>
			{% with users = form.user_ID.choices %}
			<select id="user_ID" name="user_ID" >
				{% for userid, label in users %}
				<option value="{{ userid }}" {% if userid in assigned and userid != 0 and userid != form.user_ID.data %}disabled{% endif%} {% if userid == form.user_ID.data %}selected="selected"{% endif %} >{{ label }}</option>
				{% endfor %}
			</select>
			{% endwith %}
		</p>
		{% with errors = form.user_ID.errors %}{% if  errors %}
			<ul class=errors>
			{% for error in errors %}
				<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %} {# if errors #} {% endwith %}
	</div>
	<div class="assignment-buttons data-element">
		<p>
		<span class="cancel-link" onclick="cancelModalForm()">Cancel</span>
		<input class="assignmentSave" type="button" onclick="submitModalForm('assignmentFromListForm', '{{ url_for('assignment.editFromList')}}', 'assignmentList', '{{ url_for('assignment.getAssignmentList')}}/{{ form.countEvent_ID.data | default(g.countEventID,True)}}/')" name="Save" value="Save" />
		</p>
	</div>
</form>
</div>

templates/assignment/popupErrorForm.html
{# error for AJAX response #}
{% with messages = get_flashed_messages() %} 
<div id="popupErrors" class="clear" id="flasher_contain">
{% if messages %}
 	{% for message in messages %} 
	<p class="flash">
		{{ message }}
	</p>
	{% endfor %} 
{% endif %} {% endwith %}
</div>