views/login.py
from flask import request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint
from bikeandwalk import db,app
from models import User
from views.utils import printException, cleanRecordID
from views.user import matchPasswordToHash, looksLikeEmailAddress, setUserStatus, getUserPasswordHash
from time import sleep


mod = Blueprint('login',__name__)

def setExits():
    g.title = 'Login'

@mod.route('/login', methods=['GET', 'POST'])
@mod.route('/login/', methods=['GET', 'POST'])
def login():
    setExits()
    
    if g.user and g.user != None:
        flash("Already Logged in...")
        return redirect(url_for("home"))
        
    if not request.form:
        if 'loginTries' not in session:
            session['loginTries'] = 0
        
    if request.form:
        if 'loginTries' not in session:
            #Testing that user agent is keeping cookies.
            #If not, there is no point in going on... Also, could be a bot.
            return render_template('login/no-cookies.html')
                
        if validateUser(request.form["password"],request.form["userNameOrEmail"]):
            setUserSession(request.form["userNameOrEmail"].strip())
            return redirect(url_for("home"))
        else:
            flash("Invalid User Name or Password")
        
    if 'loginTries' not in session:
        session['loginTries'] = 0
        
    #remember howmany times the user has tried to log in
    session['loginTries'] = session['loginTries'] + 1
    #slow down login attempts
    if session['loginTries'] > 5:
        sleep(session['loginTries']/.8)
        
    return render_template('login/user_login.html', form=request.form)
       
def validateUser(password,userNameOrEmail):
    if password and userNameOrEmail: 
        password = password.strip()
        userNameOrEmail = userNameOrEmail.strip()
        #Check for a password match
        passHash = getUserPasswordHash(userNameOrEmail)
        if passHash != '':
            if matchPasswordToHash(password,passHash):
                return setUserStatus(userNameOrEmail)
            
            
    return False
    
    
@mod.route('/logout', methods=['GET'])
@mod.route('/logout/', methods=['GET'])
def logout():
    session.clear()
    g.user = None
    flash("Successfully Logged Out")
    return redirect(url_for("home"))
    
    
def setUserSession(userNameOrEmail):
        session["user"] = userNameOrEmail

views/org.py
from flask import request, session, g, redirect, url_for, \
     render_template, flash, Blueprint
from bikeandwalk import db
from models import Organization
from views.utils import getTimeZones, printException, cleanRecordID

mod = Blueprint('org',__name__)

def setExits():
    g.listURL = url_for('.org_list')
    g.editURL = url_for('.org_edit')
    g.deleteURL = url_for('.org_delete')
    g.title = 'Orgnaization' ## Always singular

@mod.route('/org')
def org_list():
    if db :
        rec = Organization.query.all()
        setExits()
        return render_template('org/org_list.html', recs=rec)

    flash('Could not open Database')
    return redirect(url_for('home'))
    
# Edit the Org
@mod.route('/org/edit', methods=['POST', 'GET'])
@mod.route('/org/edit/', methods=['POST', 'GET'])
@mod.route('/org/edit/<id>/', methods=['POST', 'GET'])
def org_edit(id=0):
    setExits()
    id = cleanRecordID(id)
    if id < 0:
        flash("That is not a valid ID")
        return redirect(g.listURL)
     
    timeZones = getTimeZones()
    if not request.form:
        """ if no form object, send the form page """
        # get the Org record if you can
        rec = None
        if int(id) > 0:
            rec = Organization.query.get(id)
            
        return render_template('org/org_edit.html', rec=rec, timeZones=timeZones)
            
            
    #have the request form
    if validForm():
        if id > 0:
            rec = Organization.query.get(id)
        else:
            ## create a new record stub
            rec = Organization(request.form['name'],request.form['email'],request.form["defaultTimeZone"])
            db.session.add(rec)
        #update the record
        rec.name = request.form['name']
        rec.email = request.form['email']
        rec.defaultTimeZone = request.form["defaultTimeZone"]
        try:
            db.session.commit()
        except Exception as e:
            flash(printException('Error attempting to create '+g.title+' record.',"error",e))
            db.session.rollback()
            
        return redirect(url_for('.org_list'))
        
    # form not valid - redisplay
    return render_template('org/org_edit.html', rec=request.form, timeZones=timeZones)


@mod.route('/org/delete', methods=['GET'])
@mod.route('/org/delete/', methods=['GET'])
@mod.route('/org/delete/<id>/', methods=['GET'])
def org_delete(id=0):
    setExits()
    id = cleanRecordID(id)
    if id < 0:
        flash("That is not a valid ID")
        return redirect(g.listURL)
    
    if id > 0:
        rec = Organization.query.get(id)
        if rec:
            db.session.delete(rec)
            db.session.commit()
        else:
            flash("Record could not be deleted.")
            
    return redirect(url_for('.org_list'))
    
def validForm():
    # Validate the form
    goodForm = True
    
    if request.form['name'] == '':
        goodForm = False
        flash('Name may not be blank')
    if request.form['name'] != '':
        rec = Organization.query.filter(Organization.name == request.form['name'], Organization.ID != request.form['ID']).count()
        if rec > 0 :
            goodForm = False
            flash('That name is already in use')

    if request.form['email'] == '':
        goodForm = False
        flash('Email may not be blank')
    if request.form['email'] != '':
        rec = Organization.query.filter(Organization.email == request.form['email'], Organization.ID != request.form['ID']).count()
        if rec > 0 :
            goodForm = False
            flash('That email address is already in use for another Organization')


    return goodForm

def getName(orgID):
    orgID = cleanRecordID(orgID)
    if orgID > 0:
        org = Organization.query.get(orgID)
        if org:
            return org.name
        
    return ''
    
def getOrgDefaultTimeZone(orgID):
    orgID = cleanRecordID(orgID)
    if orgID > 0:
        org = Organization.query.get(orgID)
        if org:
            return org.defaultTimeZone

    return ""
    
    

views/user.py
from flask import request, session, g, redirect, url_for, abort, \
     render_template, flash, Blueprint
from time import time
import re
from bikeandwalk import db,app
from models import User, Organization, UserOrganization
from views.utils import printException, cleanRecordID, getOrgUsers, getUserOrgs
import hmac
import hashlib
import random
from sqlalchemy import func
#from views.login import setUserSession #user imported in login
import views.login

mod = Blueprint('user',__name__)

def setExits():
    g.listURL = url_for('.display')
    g.editURL = url_for('.edit')
    g.deleteURL = url_for('.delete')
    g.title = 'User'

@mod.route('/user/')
def display():
    setExits()
    if db :
        recs = getOrgUsers(g.orgID)
        return render_template('user/user_list.html', recs=recs)

    flash('Could not open Database')
    return redirect(url_for('index'))
    
# Edit the user
@mod.route('/user/edit', methods=['POST', 'GET'])
@mod.route('/user/edit/', methods=['POST', 'GET'])
@mod.route('/user/edit/<id>/', methods=['POST', 'GET'])
def edit(id=0):
    #printException(str(request.form)) 
    
    setExits()
    id = cleanRecordID(id)
    orgs = Organization.query.order_by(Organization.name)
    u = getUserOrgs(id)
    selectedOrgs = []
    for s in u:
        selectedOrgs.append(s.ID)
    
    if id < 0:
        flash("That is not a valid ID")
        return redirect(g.listURL)
            
    rec = None
    
    if not request.form:
        """ if no form object, send the form page """
        # get the user record if you can
        currentPassword = ""
        if id > 0:
            rec = User.query.get(id)
            currentPassword = rec.password
                
        
    else:
        #have the request form
        #ensure a value for the check box
        inactive = request.form.get('inactive')
        if not inactive: 
            inactive = "0"
        

        if validForm():
            if id > 0:
                rec = User.query.get(id)
            else:
                ## create a new record stub
                rec = User(request.form['name'],request.form['email'])
                db.session.add(rec)
                #db.session.commit() # this loads the new ID into rec
                
                rec.userName = db.null()
                rec.password = db.null()
        
            #Are we editing the current user's record?
            editingCurrentUser = ''
            if(g.user == rec.userName):
                editingCurrentUser = request.form['userName'].strip()
            else: 
                if(g.user == rec.email):
                    editingCurrentUser = request.form['email'].strip()
            
            #update the record
            rec.name = request.form['name'].strip()
            rec.email = request.form['email'].strip()
            rec.role = request.form['role'].strip()
            rec.inactive = str(inactive)
            
            user_name = ''
            if request.form['userName']:
                user_name = request.form['userName'].strip()
            
            if user_name != '':
                rec.userName = user_name
            else:
                rec.userName = db.null()
        
            # Null values in db are returned as None
            if str(rec.password) != 'NULL' and request.form['password'].strip() == '':
                # Don't change the password
                pass
            else:
                user_password = ''
                if request.form['password'].strip() != '':
                    user_password = getPasswordHash(request.form['password'].strip())

                if user_password != '':
                    rec.password = user_password
                else:
                    rec.password = db.null()
    
            try:
                db.session.commit()
                # create user_organization records
                # in the case of a new user, rec.ID is now available
                orgIDs = request.form.getlist("orgs")
                if not orgIDs:
                    orgIDs = [request.form.get('org')]
                makeUserOrgRecords(rec.ID,orgIDs)
                db.session.commit()
                
                # if the username or email address are the same as g.user
                # update g.user if it changes
                if(editingCurrentUser != ''):
                    setUserStatus(editingCurrentUser)
                    views.login.setUserSession(editingCurrentUser)
                
            
           
                
            except Exception as e:
                db.session.rollback()
                flash(printException('Error attempting to save '+g.title+' record.',"error",e))
            
            return redirect(g.listURL)
        
        else:
            # form did not validate, giv user the option to keep their old password if there was one
            currentPassword = ""
            if request.form["password"] != "" and id > 0:
                rec = User.query.get(id)
                currentPassword = rec.password
            rec=request.form

    # so the checkbox will be set on new record form
    if len(selectedOrgs) == 0:
        selectedOrgs.append(g.orgID)
            
    # display form
    return render_template('user/user_edit.html', rec=rec, currentPassword=currentPassword, orgs=orgs, selectedOrgs=selectedOrgs)
    

@mod.route('/user/delete', methods=['GET'])
@mod.route('/user/delete/', methods=['GET'])
@mod.route('/user/delete/<id>/', methods=['GET'])
def delete(id=0):
    setExits()
    id = cleanRecordID(id)
    if id < 0:
        flash("That is not a valid ID")
        return redirect(g.listURL)
    
    if id > 0:
        rec = User.query.get(id)
        if rec:
            try:
                db.session.delete(rec)
                db.session.commit()
            except Exception as e:
                flash(printException('Error attempting to delete '+g.title+' record.',"error",e))
        else:
            flash("Record could not be deleted.")
            
    return redirect(g.listURL)
    

@mod.route('/orgSwitch/<newOrg>/', methods=['GET'])
def orgSwitch(newOrg=None):
    # switch to another organization
    if g.role == 'super' and newOrg :
        session['superOrgID'] = newOrg

    return redirect(url_for('home'))        

        
def validForm():
    # Validate the form
    goodForm = True
    
    #must have at least one organization selected
    if not request.form.getlist('orgs') and not request.form['org']:
        goodForm = False
        flash("You must select at least one organization")
    
    if request.form['name'].strip() == '':
        goodForm = False
        flash('Name may not be blank')

    if request.form['email'].strip() == '':
        goodForm = False
        flash('Email may not be blank')

    if request.form['email'] != '':
        cur = User.query.filter(func.lower(User.email) == request.form['email'].strip().lower(), User.ID != request.form['ID']).count()
        if cur == 0:
            # be sure that no other user has this email as their userName. Very unlikely...
            cur = User.query.filter(func.lower(User.userName) == request.form['email'].strip().lower(), User.ID != request.form['ID']).count()

        if cur > 0 :
            goodForm = False
            flash('That email address is already in use')
        #test the format of the email address (has @ and . after @)
        elif not looksLikeEmailAddress(request.form['email']):
            goodForm = False
            flash('That doesn\'t look like a valid email address')
            
    # user name must be unique
    uName = request.form['userName'].strip()
    if uName == "None":
        uName = ""
    else :
        cur = User.query.filter(func.lower(User.userName) == request.form['userName'].strip().lower(), User.ID != request.form['ID']).count()
        if cur == 0:
            # be sure no one else has this email address as their userName... Unlikely, I know.
            cur = User.query.filter(func.lower(User.email) == request.form['userName'].strip().lower(), User.ID != request.form['ID']).count()
            
        if cur > 0 :
            goodForm = False
            flash('That User Name is already in use')
        
    passwordIsSet = ((User.query.filter(User.password != db.null(), User.ID == request.form['ID']).count()) > 0)
    
    if request.form["userName"].strip() != '' and request.form["password"].strip() == '' and not passwordIsSet:
        goodForm = False
        flash('There must be a password if there is a User Name')
        
    if len(request.form["password"].strip()) == 0 and len(request.form["password"]) != 0 and passwordIsSet:
        goodForm = False
        flash('You can\'t enter a blank password.')
    
    #passwords must match if present
    if request.form['password'].strip() != '' and request.form['confirmPassword'].strip() != request.form['password'].strip():
        goodForm = False
        flash('Passwords don\'t match.')
        
    return goodForm
    
def findUser(emailOrUserName=None,includeInactive=False):
    if emailOrUserName == None:
        return None
        
    emailOrUserName = emailOrUserName.strip().lower()
    ## locate the user with this as their email or userName
    sql = "SELECT user.*, user_organization.organization_ID FROM user join user_organization WHERE lower(user.email) = '%s' OR lower(user.userName) = '%s'"
    #sql = "SELECT * FROM user WHERE  lower(user.email) = '%s' OR lower(user.userName) = '%s'"
    sql = sql % (emailOrUserName, emailOrUserName)
    
    #Filter inactive if needed
    if not includeInactive:
        #Active user only
        sql = sql + " AND user.inactive = '0'"
    
    sql = sql + " LIMIT 1 ;"
    
    rec = db.engine.execute(sql).fetchone()
    if rec:
        return rec
        
    return None
    
def setUserStatus(emailOrUserName):
    if emailOrUserName == None:
        return False
    emailOrUserName = emailOrUserName.strip()

templates/_form_helpers.html
{% macro render_field_in_table(field) %}
  <tr><th>{% if field.type != "HiddenField" %}{{ field.label }}: {% endif %}</th><td><p {% if field.required %}class="req"{% endif %} >{{ field(**kwargs)|safe }}</p>
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
	</td></tr>
{% endmacro %}

{% macro render_field(field) %}
  <p>{% if field.type != "HiddenField" %}<strong>{{ field.label }}: </strong>{% endif %}{{ field(**kwargs)|safe }}</p>
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endmacro %}

templates/editFormButtons.html
<dd class="form_button_row" >
	<input type=submit value=Save />&nbsp;&nbsp;
	{% if rec.ID and rec.ID > 0 %}
	<a id="form_delete_link" href = "{{g.deleteURL}}{{rec.ID|default('0',true)}}/" onclick="return confirmRecordDelete();">Delete...&nbsp;&nbsp;</a>
	{% endif %}
	<a href="{{ g.listURL }}" >Cancel</a>
</dd> 

templates/flasher.html
{% with messages = get_flashed_messages() %} {% if messages %} 
<div class="clear" id="flasher_contain">
	{% for message in messages %} 
	<p class="flash">
		{{ message }}
	</p>
	{% endfor %} 
</div>
{% endif %} {% endwith %}

templates/genericEditForm.html
{% extends "layout.html" %}
{% block title %}Edit {{ g.title }}{% endblock %}
{% block body %}
	<h2>Edit {{ g.title }}</h2>
	{% if form %}
    <form class="entry" action="{{ g.editURL }}{{rec.ID|default("0",true)}}/" method="POST" enctype="multipart/form-data">
		{% include "editFormButtons.html" %}
		{% from "_form_helpers.html" import render_field_in_table %}
			{{ form.csrf_token }}
      <table class="edit-form-table">
			{% for f in form %}
				{{ render_field_in_table(f) }}
			{% endfor%}
      </table>
    </form>
	{% else %}
		<dt>No form found</dt>
	{% endif %}
{% endblock body %}

templates/index.html
{% extends "layout.html" %}
{% block title %}Admin Center{% endblock %}
{% block body %}
  <h3>Welcome to the Bike and Walk Admin Area</h3>
	{% if not g.user %}
		{% include "onlyAdmins.html" %}
	{% else %}
		{% if g.role == 'super' %}
		<p><strong>Select Org:</strong>
		<select value="orgSwitch" onchange="orgSwitch(this)">
			{% for org in orgs %}
			<option value="{{org.ID}}" {% if org.ID == g.orgID %}selected="selected"{% endif %}>{{org.name}}</option>
			{% endfor %}
		</select></p>
		<div id="super_menu" class="admin_menu">
			<h5>Super Menu</h5>
			<ul>
				<li><a href="{{ url_for('org.org_list')}}">Organization List</a></li>
				<li><a href="{{ url_for('feature.display')}}">Feature List</a></li>
				<li><a href="{{ url_for('traveler.display')}}">Traveler List</a></li>
			</ul>
		</div>
		{% endif %} {# super menu #}
		{% if g.role == 'admin' or g.role == 'super' %}
		<div class="admin_menu">
				<h5>Administration Menu</h5>
			<ul>
				<li><a href="{{ url_for('user.display')}}">User List</a></li>
				<li><a href="{{ url_for('location.display')}}">Location List</a></li>
				<li><a href="{{ url_for('count_event.display')}}">Event List</a></li>
				<li><a href="{{ url_for('report.display')}}">Reports and Exports</a></li>
			</ul>
		</div>
		{% else %}
			{% include "onlyAdmins.html"%}
		{% endif %} {# admin menu #}
	{% endif %} {# not a user #}
		<p class="clear">&nbsp;</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{% block title%}{% endblock %} - Bike and Walk</title> 
	<link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}" >
    <link rel="SHORTCUT ICON" type="image/vnd.microsoft.icon" href="{{ url_for('static', filename='favicon.ico') }}" >
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	
	<link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
	<script src="{{ url_for('static', filename='bikeandwalk.js') }}"></script>
	{% if g.tripTotalCount and g.tripTotalCount > 0 %}
	<script type="text/javascript">
		$(document).ready(function(){
				$("a#form_delete_link").hide();
		});
	</script>
	{% endif %}
    {% block head%}{% endblock %}
</head>
<body>
<div id="contain">
	<div id="dialog"></div><div id="modal-form-contain"><div id="modal-form"></div></div>
	<div>
		<a id="header_home" href="{{ url_for('home')}}"> 
			<img src="{{ url_for('static', filename='images/HeaderLogo128.png') }}" id="headerlogo" />
		</a>
		<h1><a id="header_home" href="{{ url_for('home')}}">Bike and Walk<br>Count Administration</a></h1> 
	</div>
	<div class="authbar">
		<p>
			{% if g.user %} Signed in as <em>{{ g.user }}</em> (<a href="{{ url_for("login.logout")}}" class=signout>Sign out</a>) {% else %} Not signed in. <a href="{{ url_for("login.login")}}" class=signin>Sign in</a> {% endif %} 
		</p>
		{% if g.organizationName and g.organizationName != '': %} 
		<p>
			Organization Name: <strong>{{g.organizationName}}</strong> {% if request.path != url_for('home') %}&nbsp;&nbsp;&nbsp;<a href="{{url_for('home')}}">Go to Menu</a>{%endif%} 
		</p>
		{% else %}
		{% if request.path != url_for('home') and g.user %}<p><a href="{{url_for('home')}}">Go to Admin Menu</a></p>{%endif%}
		{% if request.path != url_for('report.display') %}<p><a href="{{url_for('report.display')}}">Go to Report Menu</a></p>{%endif%}
		{% endif %} 
	</div>
	{% include "flasher.html" %}
	{% block body %}{% endblock %} 
</div>
</body>
</html>

templates/onlyAdmins.html
<p >
	You must be an Administrator to use the Administration web site.
</p>
{% include "onlyUsers.html" %}

templates/onlySupers.html
<p>
	You must be a "Super" Administrator to use this function.
</p>
{% include "onlyUsers.html" %}

templates/onlyUsers.html
<p>
	For more information about the Bike and Walk system please
	<a href="http://www.bikeandwalk.org/contact/">contact us</a> from the main web site.
</p>
<p>
	If you are an Administrator you must <a href="{{ url_for('login.login')}}" class=signin>Sign in</a> to gain access to your records.
</p>

templates/searchControls.html
<div id="searchControls">
	<form action="{{ g.mapURL | default("",True) }}" name="searchControlsForm" method="post" accept-charset="utf-8">
		<h4>Search:</h4>
		<table id="searchControlsTable" class="searchForm">
			<tr>
				{% if queryData and queryData["orgs"] %}
				<th>Org:</th>
				<td>
					<select id="searchOrgs" name="searchOrgs" class="searchSelect" {% if queryData['selectType'] and queryData['selectType'] == 'multiple' %} multiple size="4" {% endif %} >
						{% if queryData['includeAllOption'] != False %}<option value="0" {% if queryData["searchOrgs"] and '0' in queryData["searchOrgs"] %}selected{% endif %} >All</option>{% endif %}
						{% for org in queryData["orgs"] %}
							<option value="{{org.ID}}" 
								{%if queryData["searchOrgs"] and org.ID in queryData["searchOrgs"] %} selected {%endif%} 
							>{{org.name}}</option>
						{% endfor %}
					</select>
				</td>
				{% endif %}
				{% if queryData and queryData["events"] %}
				<th>Events:</th>
				<td>
					<select id="searchEvents" name="searchEvents" class="searchSelect" {% if queryData['selectType'] and queryData['selectType'] == 'multiple' %} multiple size="4" {% endif %} >
						{% if queryData['includeAllOption'] != False %}<option value="0" {% if queryData["searchEvents"] and '0' in queryData['searchEvents'] %}selected{% endif %}>All</option>{% endif %}
							{% for event in queryData['events'] %}
								<option value="{{event.ID}}" 
									{%if queryData["searchEvents"] and event.ID in queryData["searchEvents"] %} selected {%endif%} 
								>{{event.name}}</option>
							{% endfor %}
					</select>
				</td>
				{% endif %}
				{% if queryData and queryData["travelers"] %}
				<th>Travelers:</th>
				<td>
					travelers go here
				</td>
				{% endif %}
				{% if queryData and queryData["features"] %}
				<th>Features:</th>
				<td>
					Features go here
				</td>
				{% endif %}
				<th>
					<p><input id="searchButton" type="submit" name="searchButton" value="Search" /></p>
				{% if queryData['searchType'] in ('trips', 'map') %}
					<p><button id="exportButton" type="button" name="exportButton" >Export</button></p>
				{% endif %}
				</th>
			</tr>
		</table>
	</form>
	{% if queryData['searchType'] in ('trips', 'map') %}
	<div id="tripExport">
		<h4>Export Options...</h4>
		<form action="{{ g.exportURL }}" id="tripExportForm" name="tripExportForm" method="post" accept-charset="utf-8">
			<textarea style="display:none;" rows="3" cols="80" readonly id="queryDataArea" >{{ queryData|tojson|safe }}</textarea>
			<table id="exportTable" class="searchForm">
				<tr>
					<th>Export Style:</th>
					<td>
						<select id="exportStyle" name="exportStyle">
							{% if queryData['searchType'] == 'map' %}
							<option value='{{queryData['searchType']}}'>As Displayed, by Location</option>
							{% endif %}
							<option value="summary" >Summary, by Event</option>
							<option value="detail">Detail</option>
							<option value="nbpd">NBPD Report</option>
						</select>
					</td>
					<th>
						<p><input type="submit" value="Download"></p>
					</th>
				</tr>
			</table>
		</form>
		<script>
			// prevent export if search criteria has changed
			$('#exportButton').click(function(){$('#tripExport').toggle();});
			$('select.searchSelect').change(
				function(){
					$('#tripExport').hide();
					$('#exportButton').addClass('disabled').unbind('click').click(
						function(){
							alert('Selection changed.\nClick Search button first.');
							return false;
						}
					);
				}
				)
		
			// can't seem to get the json data into an input field, so append a hidden textarea
			 $("#tripExportForm").submit( function(eventObj) {
					var theQuery = $('#queryDataArea').text();
			      $('<input />').attr('type', 'hidden')
			          .attr('name', "queryData")
			          .attr('value', theQuery)
			          .appendTo('#tripExportForm');
			      return true;
			  });
		</script>
	</div>
	{% endif %}
</div>